spring:
  application:
    name: Spring-Kafka-test
  kafka:
    bootstrap-servers: 192.168.64.1:19092 #  FIXME: IP 可能會變動，請自行修改 (此處是 Host 上的 IP)
    listener:
      missing-topics-fatal: false # true: 當 @KafkaListener 嘗試訂閱不存在的 topic 時，應用將拋出異常，而不是默默地創建一個新 topic

server:
  port: 8080
  servlet:
    context-path: /roger-kafka-api

management: # Spring Actuator 監控(http://127.0.0.1:7001/my-actuator/health / http://127.0.0.1:7001/my-actuator/env)
  server:
    address: 0.0.0.0 # 允許所有來源 IP 訪問
    port: 7001 # 訪問路徑：http://localhost:7001/my-actuator/health
  endpoints:
    web:
      base-path: "/my-actuator"
      exposure:
        # include: "*" # 全開 (health,info,beans,conditions,env)
        include: "health,info,env"
  endpoint:
    health:
      show-details: always
    shutdown:
      access: none

# Log4j2 沒辦法自行指定配置文件，故必須透過 spring profile application.yml 指定不同環境配置文件
logging:
  config: classpath:log4j2-dev.yaml

# 自訂參數
emp:
  name: Roger-dev
  occupation: Software Engineer-dev